name: Deploy to S3

on:
  push:
    branches: [ "main" ]  # or your chosen branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build   # or yarn build if you use Yarn

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}  # or "us-east-1" if you prefer a fixed region

      - name: Deploy to S3
        run: aws s3 sync build/ s3://arijitpal-photography-static-site-s3 --delete
        # --delete removes files from S3 that no longer exist locally
